let href=["home.html","series.html","books.html","movies.html","about.html","contact.html","register.html"],
    icons=["home-outline","book-outline","library-outline","film-outline","map-outline","call-outline","log-in-outline"],
    text=["Home","Series","Books","Movies","About","Contact","Register"],mm=0,dd=0,dropDown="",mainMenu="",
    wilds = [
{
 poster:"https://i.pinimg.com/736x/63/4e/61/634e61f3bb050eb22a447f2d81dc98ff.jpg",
 genislik:"55 cm",
 uzunluk:"190 cm",
 speed:"60 km/h",
 isim:"leopar",
 info:"Leopar özellikleri konusuna bakıldığında sarı üzerine siyah benekleri bulunan vahşi bir kedidir. Ağırlıkları 90 kilograma kadar ulaşabilir. Uzunlukları kuyrukları da dahil edildiğinde iki buçuk metreyi bulabilir. Erkek leoparlar, dişi leoparlara göre daha iridir. Bacak boyları gövde uzunluklarına oranla diğer kedilerden daha kısa olduğundan ağaç gibi yüksek yapılara tırmanma kabiliyetleri de diğer kedilere göre daha gelişmiştir. Çoğu kişi tarafından jaguarlar ile karıştırılır. Fakat jaguarların derisindeki beneklerin içi siyah değilken, leoparların beneklerinin içi siyahtır"},
{
 poster:"https://images.pexels.com/photos/6180778/pexels-photo-6180778.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
 genislik:"75 cm",
 uzunluk:"208cm / 184cm",
 speed:"80 km/h",
 isim:"Lion",
 info:"Ormanın Kralı ve yeraltı dünyasının koruyucusu olarak görülen bir güneş hayvanıdır. Bu egemen kedinin gücü, bilgelik, gurur, gençlik, diriliş, güvenlik, koruma, adaleti temsil eder. Aslan, güneş ve kral sembolünün dünyevi yönü olan “Kronik” (yeryüzü ile ilgili) doğayı temsil eden eril ilkenin “Teriomorfik” (insandan hayvana) temsilidir. Ayrıca, savaşçı bir hayvan olmanın yanı sıra sağlıklı agresif dürtüleri öne süren birleşme ve gururla da ilişkilidir."},
{
 poster:"https://images.pexels.com/photos/2055100/pexels-photo-2055100.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
 genislik:"65 cm",
 uzunluk:"2.5 / 3 metre",
 speed:"65 km/h",
 isim:"tiger",
 info:"Diğer kedigillere göre daha paylaşımcıdırlar. Kaplanlar 6 metrenin üstünde ileriye zıplayabilirler. Zıpladıklarında 5 metre yükseğe kadar da çıkabilirler. Genelde kaplanlar kurbanlarının boyunlarından ısırarak öldürürler fakat pençe darbesiyle bir ayının kafasını bile kırabilir."},
{
 poster:"https://images.pexels.com/photos/10526601/pexels-photo-10526601.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
 genislik:"94 m",
 uzunluk:"1.5 m",
 speed:"130 km/h",
 isim:"cheetah",
 info:"Kedigiller familyasının bir üyesi olup, diğer memelilerden daha hızlı koşabilmesiyle bilinir. Günümüzde türün çoğunluğu Güney ve Doğu Afrika'da yaşar."},
{
 poster:"https://e1.pxfuel.com/desktop-wallpaper/975/226/desktop-wallpaper-big-cat-leopard-feline-jaguar-fur-predator-animal-wild-jaguar-phone-thumbnail.jpg",
 genislik:"60 cm",
 uzunluk:"1.8 m",
 speed:"80 km/h",
 isim:"jaguar",
 info:"Kedigiller familyasından ve Panthera cinsinin dört büyük kedisinden biri olan bir Yeni Dünya memelisidir. Diğer üç büyük kedi, Eski Dünya’nın kaplan, aslan ve parstır. Kaplan ve aslandan sonra en büyük üçüncü kedi olan jaguar Batı Yarımküresinin en büyük ve en güçlü kedisidir."},
{
 poster:"https://mfiles.alphacoders.com/638/638279.jpg",
 genislik:"80 cm",
 uzunluk:"150 cm",
 speed:"56 km/h",
 isim:"Grilliz Bear",
 info:"Ursidae familyasının etçil memelileridir. Ayılar Köpeğimsiler veya köpek benzeri etoburlar olarak sınıflandırılır. Her ne kadar sadece sekiz ayı türü mevcut olsa da, Kuzey yarımkürede ve kısmen Güney yarımkürede çok çeşitli habitatlarda görülürler."},
{
 poster:"https://images.unsplash.com/photo-1590420485404-f86d22b8abf8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8NHx8fGVufDB8fHx8&w=1000&q=80",
 genislik:"85 cm",
 uzunluk:"106 cm",
 speed:"60 km/h",
 isim:"wolf",
 info:"Avrasya ve Kuzey Amerika'ya özgü ve Canis cinsinden iri bir memelidir. Otuzdan fazla Canis lupus alt türü tanınmakta ve bozkurt denildiğinde günlük konuşma dilinde evcilleştirilmemiş ve yabani alt türler anlaşılmaktadır."},
{
 poster:"https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcRCR5y9m8mfRMs5GSmBTBBe2pw5Xxnr4nLwng7UyiIHJ9AMmZFmqrj1ZBbHijT2vXXJ",
 genislik:"2.3 m",
 uzunluk:"100 cm",
 speed:"320 km/h",
 isim:"dark eagle",
 info:"Atmacagiller familyasına üyedir. Kartal türleri çok geniş bir yelpazede dağılan yırtıcı kuşları kapsar. Türkiye'de genellikle dağlık bölgelerde yaşarlar."},
{
 poster:"https://images.pexels.com/photos/1358417/pexels-photo-1358417.jpeg?auto=compress&cs=tinysrgb&w=600",
 genislik:"1.5 m",
 uzunluk:"65 cm",
 speed:"190 km/h",
 isim:"hawk",
 info:"Atmacagiller familyasından Kuzey Amerika'da yaygın yırtıcı kuş türü. Batı Alaska'dan kuzey Kanada'ya, güneyde Panama'ya ve Karayipler'e kadar Kuzey Amerika'nın büyük bölümünde ürer ve bu bölgede en yaygın Buteo türlerinden biridir."},
{
 poster:"https://damion.club/uploads/posts/2022-01/thumbs/1642920361_9-damion-club-p-ptitsi-stervyatniki-9.jpg",
 genislik:"1.7 m",
 uzunluk:"74 cm",
 speed:"48 km/h",
 isim:"vulture",
 info:"Yeni dünya akbabaları familyasını ve atmacagiller familyasına ait Eski Dünya akbabaları alt familyasını oluşturan leş yiyici kuşların ortak ismidir. Akbaba terimi belirli bir taksonomik grubu karşılamaz. Günümüzde 16'sı Eski Dünya'ya ve 7'si Yeni Dünya'ya ait 23 akbaba türü bulunur."},
{
 poster:"https://3.bp.blogspot.com/-j2DTzPUSxIY/WNPjj-pRByI/AAAAAAAATTI/79_fzro58Qc_TBl4rioo6xCY9Y8tXn0uQCLcB/s1600/Cute-Zebra-Wallpaper%2B%252830%2529.JPG",
 genislik:"1.3 m",
 uzunluk:"2.6m",
 speed:"65 km/h",
 isim:"zebra",
 info:"Atgiller familyasını oluşturan tek cins Equus'un zebraları içeren Hippotigris alt cinsinde sınıflanan bir türdür. Ova zebrası olarak da anılan bu türün daha önceleri çözülmemiş olan sınıflaması 2004'te yayınlanmış bir araştırmayla aydınlatılmıştır."},
{
 poster:"https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQVtv8s0UPfAk9z-y_PMve7sVi9Q2jsJxTa0YV1fnRgfIympdhhj2OlfRnW1XCxPUEG",
 genislik:"55cm",
 uzunluk:"5.5 m",
 speed:"60 km/h",
 isim:"zürafa",
 info:"Soyu tükenmemiş canlılar arasında karada yaşayan en uzun ve gevişgetirenler arasında da en büyük; Afrika’da yaşayan çift toynaklı memelidir. Bilimsel tür adı deveye benzer şekline ve leoparda benzeyen beneklerine ithafen verilmiştir."},
]; // wilds array end.